GET http://localhost:4000/ping

###
GET http://localhost:4000/eventos

###
GET http://localhost:4000/eventos/evento-fullstack

###
GET http://localhost:4000/eventos/5e25282b-cde5-45ff-9436-c4320d7c2f6f

###
GET http://localhost:4000/eventos/validar/evento-fullstack/21ff36d7-8fa7-495e-9339-d1687458b660

###
POST http://localhost:4000/eventos/acessar
Content-Type: application/json

{
  "id": "65965e1c-8055-4795-b4a3-da93bbe97e31",
  "senha": "familia2024!"
}

###
POST http://localhost:4000/eventos/reuniao-familia-oliveira/convidado
Content-Type: application/json

{
  "id": "65965e1c-8055-4795-b4a3-da93bbe97e31",
  "nome": "Igor Cerqueira",
  "email": "igo@email.com",
  "confirmado": true,
  "possuiAcompanhantes": true,
  "qtdeAcompanhantes": 3
}
