GET http://localhost:4000/ping

###
GET http://localhost:4000/eventos

###
GET http://localhost:4000/eventos/open-house-igao

###
GET http://localhost:4000/eventos/5e25282b-cde5-45ff-9436-c4320d7c2f6f

###
GET http://localhost:4000/eventos/validar/evento-/21ff36d7-8fa7-495e-9339-d1687458b660

###
POST http://localhost:4000/eventos/acessar
Content-Type: application/json

{
  "id": "5f476adf-33de-4f35-a7a9-90065b7abdee",
  "senha": "frameworks2025"
}

###
POST http://localhost:4000/eventos/open-house-igao/convidado
Content-Type: application/json

{
  "nome": "Milvio Sousa",
  "email": "msousa@email.com",
  "confirmado": true,
  "possuiAcompanhantes": true,
  "qtdeAcompanhantes": 1
}

###
POST http://localhost:4000/eventos
Content-Type: application/json

{
    "alias": "open-house-igao",
    "nome": "Open house do igão",
    "data": "2025-12-31T23:00",
    "local": "São Paulo",
    "descricao": "Evento de tecnologia",
    "senha": "frameworks2025",
    "imagem": "https://www.formacao.dev/assets/img/formacao-dev.png",
    "imagemBackground": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQ-0_VdF_lcXATRHDUaaI0AQCt8R6Y_ShR3A&s",
    "publicoEsperado": 1000,
    "convidados": [
        {
            "nome": "Leonardo Leitão",
            "email": "leonardo@formacao.dev",
            "confirmado": true,
            "possuiAcompanhantes": true,
            "qtdeAcompanhantes": 10
        }
    ]
}